### ISSUE TITLE
Do you support Automatically Defined Functions?

### ISSUE THREAD

**Issue by odats** [ShuhuaGao/geppy#11]

**Comment by ShuhuaGao** [comment]
Sorry, it doesn't support ADF yet.

**Comment by sayin** [comment]
Hi,
1)   When I increase the number of genes to more than 2, how do I add more linker operators using toolbox.register.
2)  When my best model contains trigonometric functions such as sin or cos, I am getting keyError: 'sin' or 'cos' when I simply the model using  gep.simply(best_ind)
