### ISSUE TITLE
How to add more symbolic functions into simplification.py?

### ISSUE THREAD

**Issue by Hoankaka15** [ShuhuaGao/geppy#15]
Hi Shuhua,

I am trying to add more symbolic functions into GEPPY but have trouble with several function, e.g., pow, exp. Could you please give me some directions?

Thanks,
Hoan Nguyen

**Comment by bozhang213** [comment]
Hi, as seen in this example: https://github.com/ShuhuaGao/geppy/blob/master/examples/sr/numerical_expression_inference-ENC.ipynb

Similar as input[5]:
'''
pset.add_function(operator.add, 2)
'''

you can just do:
'''
pset.add_function(myFunction, 3)
'''
where __myFunction__ is the function you have defined, __3__ is the number of parameters it accepts.

**Comment by Hoankaka15** [comment]
Hi Bo Zhang,

Thank you for your quick return.
I have set
pset.add_function(operator.pow, 2)
and tested a small data given as y=a^b. However, after running, the GEPPY gave me the results as follow:
"""
add(
	pow(A, B),
	pow(A, B)
)
Please provide the symbolic function mapping for 'pow' in symbolic_function_map
"""
Also, I try to added the 'pow' function into symbolic_function_map, but still cannot simplify the results.

Please give me some advice.

Thank you,
Hoan Nguyen

**Comment by bozhang213** [comment]
Hi I also encountered this problem before. I remembered that a function defined by myself could not be simplified. The simplification process uses the sympy package and maybe it doesn't support many operators... The source code for simplification is in geppy/support/simplification.py, you may check how the author of geppy employs the sympy and whether sympy support self-defined simplifying logic. I'm not sure about that, sorry.

**Comment by ShuhuaGao** [comment]
> Hi Bo Zhang,
> 
> Thank you for your quick return.
> I have set
> pset.add_function(operator.pow, 2)
> and tested a small data given as y=a^b. However, after running, the GEPPY gave me the results as follow:
> """
> add(
> pow(A, B),
> pow(A, B)
> )
> Please provide the symbolic function mapping for 'pow' in symbolic_function_map
> """
> Also, I try to add the 'pow' function into symbolic_function_map, but still cannot simplify the results.
> 
> Please give me some advice.
> 
> Thank you,
> Hoan Nguyen

Hi, Hoan,
Regarding the above simplification issue, note that 
+ Such simplification is just for postprocessing purpose, i.e., after you have evolved your model.
+ I don't think `sympy` supports the simplication of custom functions. However, as for the example you postes, it can certainly handle. You should not define your own `pow` function, because Python has a built-in one, and `sympy` recognizes it. Please see the following snippet:
```python
import sympy as sp
import operator as op
A, B = sp.symbols('A B')
sp.simplify(op.add(op.pow(A, B), op.pow(A, B)))
# it will produce 2*A**B
```
Thus, you can register your own power function to `simplify` as `operator.pow`. Anyway, since it is a built-in function, I will add it to the `DEFAULT_SYMBOLIC_FUNCTION_MAP` in geppy/support/simplification.py.

**Comment by Hoankaka15** [comment]
Hi Shuhua,

Thank you for your direction. It works perfectly now.

Best regards,
Hoan Nguyen

**Comment by ShuhuaGao** [comment]
I just made a commit to add the "pow" function to the default map. If you pull the lasted version, you need do nothing special now. Just `add_function(operator.pow, 2)` is enough.
