### ISSUE TITLE
can you explain the gep_simple method outputs-nevals?

### ISSUE THREAD

**Issue by nickhuangxinyu** [ShuhuaGao/geppy#30]
i dont understand the meanings of nevals.

And, can you explain how the mate happens?

assume i have a population(n=50), which produce 50 expressions.

how they mate? The permution of 50 expr should be 50*49/2.

I think it wont do that many times of mate, so, how it select parents and generate offstring?

Thanks, i am working on gp, and i think geppy is very friendly.

**Comment by ShuhuaGao** [comment]
Hi, you can find details in this [file](https://github.com/ShuhuaGao/geppy/blob/master/geppy/algorithms/basic.py). Nonetheless, I will make some brief explanation below.

- The first step is selection. `N` individuals are chosen as the *offspring*. Then, we apply mutation and crossover to the offspring.
-  You can see from the [`_apply_crossover`](https://github.com/ShuhuaGao/geppy/blob/master/geppy/algorithms/basic.py#L44) here that the recombination is not done for each possible pair of individuals (i.e., no permutation).  Instead, crossover only happens between individuals 0 and 1, 2 and 3, 4 and 5,  ..., in a sequential way (subject to the crossover probability). If, say, individuals A and B are recombined into two children A' and B', then A and B are replaced by A' and B' immediately in the *offspring* population.
-  In the final offspring, if an individual is produced by mutation or crossover, then its fitness is labeled *invalid* and will be evaluated in the next generation (see [this line](https://github.com/ShuhuaGao/geppy/blob/master/geppy/algorithms/basic.py#L98)). By contrast, if an individual is simply a copy of an original one, then there is no need to evaluate it again to reduce computational cost. Thus, the `neval` is just the number of invalid children that need reevaluation, which keeps changing among generations. If you are writing a paper and want to analyze the time complexity, simply view `neval` as `N` in the big-O notation.
