### ISSUE TITLE
How can I run the setup.py 

### ISSUE THREAD

**Issue by wzypersist** [ShuhuaGao/geppy#31]
i can't run setup.py on pycharm successfully.

**Comment by ShuhuaGao** [comment]
Just install it by `pip install geppy`.

**Comment by wzypersist** [comment]
i have already installed geppybut when i run setup.py&nbsp;
turns out the result like in the picture&nbsp;
how can i resolve it&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuhua Gao"<notifications@github.com&gt;; 
发送时间: 2020年11月10日(星期二) 晚上9:58
收件人: "ShuhuaGao/geppy"<geppy@noreply.github.com&gt;; 
抄送: "小精灵"<935610996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ShuhuaGao/geppy] How can I run the setup.py  (#31)





 
Just install it by pip install geppy.

**Comment by ShuhuaGao** [comment]
No need to run setup.py.  Please check the examples to see how to use `geppy`.
