### ISSUE TITLE
how to assign some illegal operation which would not be search

### ISSUE THREAD

**Issue by LJingnan** [ShuhuaGao/geppy#33]
hello, I have designed some operator, for example

f(x, n):
   ....

the second param must be constant int. How can I make a rule that the algorithm would not waste time searching.

**Comment by ShuhuaGao** [comment]
`geppy` is not strongly-typed GP. Thus, there is currently no way to enforce that `n` is an integer. If you know the value of `n`, you may define `g(x) = f(x, 3)` instead (assuming `n=3`).

**Comment by LJingnan** [comment]
I see. So  I come up with a substitution: judging the type in the function and if the type is illegal, return nan for example, when the evaluation observe a nan return, the evaluation score would be -10000

**Comment by LJingnan** [comment]
I wonder whether it is possible that I can strict the input type of the function: for example:

f(x1, x2)

x1 and x2 must be variable but not constant terminal, so a mutation would not mutate x2 with a constant terminal.

**Comment by ShuhuaGao** [comment]
In that case, you have to change the source code of `mutate`.

**Comment by ShuhuaGao** [comment]
> if the type is illegal, return nan for example

If this is not efficient, i.e., too many `nan`s, you may consider correct the argument inside `f`, for example, round `3.2` to 3.

**Comment by LJingnan** [comment]
I wonder whether it is possible that I can strict the input type of the function: for example:

f(x1, x2)

x1 and x2 must be variable but not constant terminal, so a mutation would not mutate x2 with a constant terminal.

**Comment by LJingnan** [comment]
> In that case, you have to change the source code of `mutate`.

yes, I think I should change the source code of mutate and the init_repeat.

**Comment by LJingnan** [comment]
Thank you so much
