### ISSUE TITLE
If I changed your source code a littile, is it right to re-install from source again?

### ISSUE THREAD

**Issue by RobinWenqian** [ShuhuaGao/geppy#36]
Sorry to bother again. I git clone this repo and change some code following your advice. Then is it right to just 'pip install .' again to use modified repo?

**Comment by ShuhuaGao** [comment]
yes, it's right.  See the instructions https://github.com/ShuhuaGao/geppy#from-source.

**Comment by RobinWenqian** [comment]
It works fine, thank you so much.
