### ISSUE TITLE
Save an individual, or how to create an individula knowing its expression

### ISSUE THREAD

**Issue by TOP1RM** [ShuhuaGao/geppy#40]
Hello,

I am using geppy to test it on flow control, the context is symbolic regression. To avoid restart evolutions, I want to be able to create an individual from a known expression (for instance x+y*z-2).

I launch an evolution, at the end I get my best individual thanks to the hall of fame, then I print it and I get for instance this output :

mul(
	mul(protected_div(add(protected_div(sub(y, z), x), y), sub(protected_div(y, -0.9790698363740189), add(z, x))), x),
	mul(protected_div(add(protected_div(sub(y, z), y), x), sub(protected_div(y, -0.9790698363740189), add(z, z))), x)
)

I want to make some post processing with matplotlib, and I need to use this best individual without restarting the whole evolution. How can I use the print output to create directly this individual and use it in my postprocessing script ?

Thanks and regards,
Rémi MOCHON

**Comment by ShuhuaGao** [comment]
Well, is it good for you to save the individual directly using, e.g., `pickle`? That is, no need to print it as a text form.

**Comment by TOP1RM** [comment]
> Well, is it good for you to save the individual directly using, e.g., `pickle`? That is, no need to print it as a text form.

Yes, thank you !
Rémi MOCHON
