### ISSUE TITLE
Issue with linker function

### ISSUE THREAD

**Issue by JoachDominique** [ShuhuaGao/geppy#7]
Hello, 

I am using your code for a project involving GEP. 
When using the linker function "operator.mul" you can only have two genes in your optimisation.
if you try a different number (for example 4 genes) I get the error : "op_mul expected 2 arguments, got 4".
Am I doing something wrong? Shouldn't I be able to use any number of gene with a given kind of linker? 

I can solve this by defining a new class for linker that take four input variables but It results in problem during the simplification.

Thank you very much this code, it is very helpfull.

**Comment by ShuhuaGao** [comment]
Hi, 

Yes, if there are *n* genes in a chromosome, then you need to provide a linker function which can accept *n* parameters. Besides, to utilize the symbolic simplification, a corresponding symbolic function has to be given.  You can check a similar issue [here](https://github.com/ShuhuaGao/geppy/pull/6).

**Comment by JoachDominique** [comment]
Hello,

Thank you very much for your answer. It works now.
In the future, I would like to have a linking function that evolve as a gene during the optimization (as in the homeotic gene formulation in Ferreria book p47). 
In your opinion how would be the best way to do that?

**Comment by ShuhuaGao** [comment]
Hi, 

This evolving linker function has not been implemented in the current Geppy yet. If you really need it, I think you can start by defining a custom class that inherits `Chromosome` but with an additional domain/attribute containing the linker function. Then, you need to implement your own mutation/crossover operations such that the linker can be evolved. Of course, you could reuse the current code, if possible, in your own implementation.

**Comment by waynezw0618** [comment]
Hello Again Gao & Joach
I am trying geppy to fit N 3X3 tensor Bij with two scalar list I1,I2 of size N and two 3X3 tensor list V1,V2 with fitness defined as tensorDot(Bij, PBij)/(tensordot(Bij,Bji)*tensordot(PBij, PBji)). but I get errors in my evaluation function like this:
[[ATraceback (most recent call last):
  File "testGEPPY_DNS.py", line 109, in <module>
    stats=stats, hall_of_fame=hof, verbose=True)
  File "/Users/weizhang/software/backup/geppy-master/geppy/algorithms/basic.py", line 100, in gep_simple
    for ind, fit in zip(invalid_individuals, fitnesses):
  File "testGEPPY_DNS.py", line 71, in evaluate
    Rp_i=np.array([[Yp[i,1],Yp[i,2],Yp[i,3]],[Yp[i,2],Yp[i,4],Yp[i,5]],[Yp[i,3],Yp[i,5],Yp[i,:6]]])
IndexError: too many indices for array

here is my evaluation function:
`def evaluate(individual):
    """Evalute the fitness of an individual: MSE (mean squared error)"""
    func = toolbox.compile(individual)
    Yp = np.array(list(map(func,T1,T2,T3)))   # predictions with the GEP model
    
    #print (np.shape(Yp),Yp)
    a=0
    b=0
    c=0
    for i in range(size):
       Ri=np.array([[bij[i,1],bij[i,2],bij[i,3]],[bij[i,2],bij[i,4],bij[i,5]],[bij[i,3],bij[i,5],bij[i,:6]]])
       Rp_i=np.array([[Yp[i,1],Yp[i,2],Yp[i,3]],[Yp[i,2],Yp[i,4],Yp[i,5]],[Yp[i,3],Yp[i,5],Yp[i,:6]]])
    #   print (Ri,np.shape(Ri))
       a=a+np.tensordot(Rp_i,Ri)
       b=a+np.tensordot(Ri,Ri.T) 
       c=c+np.tensordot(Rp_i,Rp_i.T) 

    return a/(b*c),
`

**Comment by waynezw0618** [comment]
Hello Again Gao & Joach

I am trying geppy to fit N 3X3 tensor Bij with two scalar list I1,I2 of size N and two 3X3 tensor list V1,V2 with fitness defined as tensorDot(Bij, PBij)/(tensordot(Bij,Bji)*tensordot(PBij, PBji)). but I get errors in my evaluation function like this:
[[ATraceback (most recent call last):
File "testGEPPY_DNS.py", line 109, in 
stats=stats, hall_of_fame=hof, verbose=True)
File "/Users/weizhang/software/backup/geppy-master/geppy/algorithms/basic.py", line 100, in gep_simple
for ind, fit in zip(invalid_individuals, fitnesses):
File "testGEPPY_DNS.py", line 71, in evaluate
Rp_i=np.array([[Yp[i,1],Yp[i,2],Yp[i,3]],[Yp[i,2],Yp[i,4],Yp[i,5]],[Yp[i,3],Yp[i,5],Yp[i,:6]]])
IndexError: too many indices for array

here is my evaluation function:
`def evaluate(individual):
    """Evalute the fitness of an individual: MSE (mean squared error)"""
    func = toolbox.compile(individual)
    Yp = np.array(list(map(func,T1,T2,T3)))   # predictions with the GEP model
    
    #print (np.shape(Yp),Yp)
    a=0
    b=0
    c=0
    for i in range(size):
       Bi=np.array([[bij[i,1],bij[i,2],bij[i,3]],[bij[i,2],bij[i,4],bij[i,5]],[bij[i,3],bij[i,5],bij[i,:6]]])
       PB_i=np.array([[Yp[i,1],Yp[i,2],Yp[i,3]],[Yp[i,2],Yp[i,4],Yp[i,5]],[Yp[i,3],Yp[i,5],Yp[i,:6]]])
    #   print (Ri,np.shape(PB))
       a=a+np.tensordot(PB_i,Ri)
       b=a+np.tensordot(PB,PB.T) 
       c=c+np.tensordot(PB_i,PB_i.T) 

    return a/(b*c),
`

I tried print the PB, seems give me a array of(N,0) rather than expected (N,3,3)
can you please give me some suggestion

**Comment by waynezw0618** [comment]
sorry the predicted B PB is of size (N,1)
