### ISSUE TITLE
cannot install geppy

### ISSUE THREAD

**Issue by grace9796** [ShuhuaGao/geppy#8]
Hi, I cannot install geppy neither by pip nor by cd geppy. I'd like to ask for solution. Thanks! 

<img width="609" alt="螢幕快照 2019-03-31 下午7 28 16" src="https://user-images.githubusercontent.com/32963721/55288501-2c781d00-53eb-11e9-816e-bb889eaaa1e4.png">

**Comment by bolz213** [comment]
clone the geppy repository, then cd to the directory of geppy and you may try: ''pip install -e .''
________________________________

**Comment by grace9796** [comment]
it does work! thanks a lot!
