### ISSUE TITLE
how to implement multigenes with different head length?

### ISSUE THREAD

**Issue by grace9796** [ShuhuaGao/geppy#9]
Hi there,
I'm trying use GEP to evolve trading rules(EDT-RNC) to detect buy/sell signal, but I have trouble in setting parameters.
I've got four genes in one chromosome with length of different heads and RNC arrays. The example shows that fixed head length and rnc array.
I'd like to ask for help that how should I rewrite the code of multigenes in the chromosome?
Words are not enough to express my gratitude.
<img width="566" alt="螢幕快照 2019-04-02 下午3 32 19" src="https://user-images.githubusercontent.com/32963721/55384169-8ba96f00-555c-11e9-9948-100de7abb00d.png">

**Comment by ShuhuaGao** [comment]
Hi, you can try the class method of Chromosome `Chromosome.from_genes` [here](https://github.com/ShuhuaGao/geppy/blob/030504eb64d2e63555b2fdab1699b9ab0f5bc343/geppy/core/entity.py#L463). To begin with, you need to create the four genes separately and assemble them into a list, which is the `genes` parameter of `Chromosome.from_genes` .

Is it necessary to use genes with various header lengths? Maybe you can set them all to the maximum value of the four. With different gene structures, it is not convenient to follow the *toolbox* style given in the examples. That is, you have to write your own code to  breed individuals.

**Comment by grace9796** [comment]
Another question for building EDT-RNC. The example in GEP_RNC_for_ML_with_UCI_Power_Plant_dataset is kind of regression problem.
I'd like to ask how could I use geppy to practice as pic below (classification).
<img width="523" alt="螢幕快照 2019-04-08 下午1 36 37" src="https://user-images.githubusercontent.com/32963721/55700821-5d67db80-5a03-11e9-9447-35a0d8bd02fd.png">

**Comment by ShuhuaGao** [comment]
Hi, there is nothing special about classification.  Generally, we need to follow two steps in the evaluation function:
+ Decode the chromosome into a solution in the problem space. Here it seems the expression tree translated from the chromosome is just a decision tree.
+ Score the solution obtained according to your own criterion. Here, the score may represent the classification accuracy or anything you like. The only requirement is that a better solution should be assigned a higher fitness.

Thus, you mainly need to customize the _evaluate_ function to meet your own need.
